compilation fixes
lolishinshi/imsearch pull request #4
Opened 2021-12-05 08:38 UTC by MichaelMai2000

根据自己编译的时候走的弯路，修复了一些小问题。

2021-12-07 02:11 UTC, Aloxaf requested changes
感谢关注

2021-12-07 02:11 UTC, Aloxaf commented on README.md
> +2. `rustup run nightly cargo install --git https://github.com/lolishinshi/imsearch`
此处可以直接使用 `cargo +nightly install`

2021-12-07 02:11 UTC, Aloxaf commented on src/config.rs
> +            flann::SearchParams::new(32, 0.0, true).expect("failed to build SearchParams"),
此处存疑，`flann::SearchParams::new` 的签名是 
```rust
pub fn new(checks: i32, eps: f32, sorted: bool, explore_all_trees: bool) -> Result<crate::flann::SearchParams>
```
参数数量明显对不上，请确认

2021-12-07 02:11 UTC, Aloxaf commented on src/main.rs
> +                Err(e) => eprintln!("[ERR] {}: {}\n{:?}", entry.display(), e, e.backtrace()),
[anyhow::Error::backtrace](https://docs.rs/anyhow/1.0.51/anyhow/struct.Error.html#method.backtrace)  此处直接返回了 `&Backtrace`，用 `{}` 输出应该也没问题

2021-12-08 13:33 UTC, MichaelMai2000 commented on README.md
> +2. `rustup run nightly cargo install --git https://github.com/lolishinshi/imsearch`
好的。
我其实不怎么了解，只是试通一个能用的。

2021-12-08 13:47 UTC, MichaelMai2000 commented on src/config.rs
> +            flann::SearchParams::new(32, 0.0, true).expect("failed to build SearchParams"),
这一处是未修改时无法通过编译，警告 `flann::SearchParams::new_1` 不存在。我修改成了存在的且最接近的 `flann::SearchParams::new` 。

签名参考了 C++ 版本 https://github.com/flann-lib/flann/blob/1d04523268c388dabf1c0865d69e1b638c8c7d9d/src/cpp/flann/util/params.h#L63 。
`SearchParams(int checks_ = 32, float eps_ = 0.0, bool sorted_ = true ) :`

不太熟悉 Rust ，不过 https://docs.rs/opencv/0.39.0/opencv/flann/struct.SearchParams.html 这里似乎也是一样的。
`pub fn new(checks: i32, eps: f32, sorted: bool) -> Result<SearchParams>`

以上两处和你提到的签名并不一致，同存疑。

2021-12-08 14:13 UTC, MichaelMai2000 commented on src/main.rs
> +                Err(e) => eprintln!("[ERR] {}: {}\n{:?}", entry.display(), e, e.backtrace()),
确实是一个我自己造成的遗留问题。

此处不使用 `nightly` 则会出现编译错误：
```
error[E0658]: use of unstable library feature 'backtrace'
   --> src/main.rs:108:79
    |
108 |                 Err(e) => eprintln!("[ERR] {}: {}\n{}", entry.display(), e, e.backtrace()),
    |                                                                               ^^^^^^^^^
    |
    = note: see issue #53487 <https://github.com/rust-lang/rust/issues/53487> for more information

error[E0277]: `Option<&Backtrace>` doesn't implement `std::fmt::Display`
   --> src/main.rs:108:77
    |
108 |                 Err(e) => eprintln!("[ERR] {}: {}\n{}", entry.display(), e, e.backtrace()),
    |                                                                             ^^^^^^^^^^^^^ `Option<&Backtrace>` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `Option<&Backtrace>`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = note: this error originates in the macro `$crate::format_args_nl` (in Nightly builds, run with -Z macro-backtrace for more info)
```

使用 `nightly` 则通过编译。

所以还需要修改吗？

2021-12-08 14:32 UTC, MichaelMai2000 commented on README.md
> +2. `rustup run nightly cargo install --git https://github.com/lolishinshi/imsearch`
fixed by 7a6bb04.

2022-04-29 02:02 UTC, Aloxaf commented
今天在  Ubuntu18.04 上编译了一下，似乎和 opencv 的版本有关……

2025-04-25 07:53 UTC, closed without merging